FROM jmeegan607/geoset
USER root
RUN uv pip install --python /app/.venv/bin/python playwright && playwright install-deps && /app/.venv/bin/playwright install chromium
COPY docker/pythonpath_dev/superset_config_docker_full.py /app/docker/pythonpath_dev/superset_config_docker.py
USER superset
